update editor content to not have html tags returned
SpringRoll/springroll.io pull request #7
Opened 2019-11-07 20:44 UTC by 902seanryan

The `$event.htm`l at line 75 was returning the editor text with the appropriate HTML tags. Switched it over to `$event.text` which returns just text with a newline and added `.trim()` to strip that off.

2019-11-08 15:42 UTC, chipbell4 approved these changes

2019-11-08 15:42 UTC, chipbell4 commented
I approved this, but we can update your internal editor config to shrink down this diff a bit? There's a lot of changes that are single to double quotes.

2019-11-13 19:07 UTC, chipbell4 requested changes
Did a quick smoke test and I'm seeing test input backwards in Firefox (may occur across browsers)

2019-11-22 19:56 UTC, 902seanryan commented
> Did a quick smoke test and I'm seeing test input backwards in Firefox (may occur across browsers)
There was some weirdness with the two way data binding that was updating the `content` property twice and forcing the cursor to the starting position in the editor. No idea why that's what happens but it's fixed.

2019-12-09 18:29 UTC, chipbell4 approved these changes

2019-12-09 18:36 UTC, merged